version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson_38
    restart: always
    ports:
      - '80:80'
    depends_on:
      - api

  api:
    image: marla4/planner:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8000:8000
    environment:
      DB_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    command: >
      sh -c "python3 manage.py runserver 0.0.0.0:8000"

  migrations:
    image: marla4/planner:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    environment:
      DB_HOST: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SECRET_KEY: ${SECRET_KEY}
      SOCIAL_AUTH_VK_OAUTH2_KEY: ${SOCIAL_AUTH_VK_OAUTH2_KEY}
      SOCIAL_AUTH_VK_OAUTH2_SECRET: ${SOCIAL_AUTH_VK_OAUTH2_KEY}

    depends_on:
      postgres:
        condition: service_healthy
    command: >
      sh -c "python3 manage.py makemigrations &&
            python3 manage.py migrate"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: marla
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: todolist
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U marla -d todolist" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: