version: "3.9"
services:
  api:
    build:
      context: .
    ports:
      - 80:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/app/.env
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: td
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./.docker_env:/app/.env
    command: python manage.py migrate


