version: "3.9"
services:
  front:
    image: sermalenk/skypro-front:base
    ports:
      - 8080:80
    depends_on:
      - api
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./env:/planner/.docker_env
  migrations:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
    volumes:
      - ./env:/planner/.docker_env
    command: python3 manage.py migrate
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: td
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

