version: "3.9"
services:
  api:
    image: sermalenk/skypro-front:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
    - 80:8000
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./docker_config.py:/code/config.py
  migrations:
    image: marla4/planner_migrations_1:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./docker_config.py:/code/config.py
    command: django db upgrade
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./postgres-data:/var/lib/postgresql/data